/**
 * helpers/elements/program-mgmt.helper.ts
 * ──────────────────────────────────────────────────────────────────────────────
 * Locators AND high-level action helpers for the Program Management feature.
 *
 * Structure:
 *   1. Element factories  – return raw Locator objects, NO side-effects.
 *   2. Action helpers     – `async` functions that accept `page` (and optionally
 *      data) and perform a meaningful business step (e.g. fillTabProgram).
 *
 * Rules (see agents.md):
 *   ✅ Element factories MUST NOT contain `await` or interaction calls.
 *   ✅ Action helpers import element factories and orchestrate clicks/fills.
 *   ✅ All names are camelCase, prefixed by their role:
 *       btn*, input*, dropdown*, checkbox*, tab*, textarea*, upload*
 * ──────────────────────────────────────────────────────────────────────────────
 */

import { Page } from '@playwright/test';
import { sidebarElements } from './global.elements';
import { form_daftar_program } from '../data.helper';

// ══════════════════════════════════════════════════════════════════════════════
// SECTION 1 – ELEMENT FACTORIES
// ══════════════════════════════════════════════════════════════════════════════

// ── Sidebar Navigation to Program Management ──────────────────────────────────

export const programMgmtNavElements = (page: Page) => ({
  btnManageProgram:      sidebarElements(page).btnManageProgram,
  linkProgramManagement: sidebarElements(page).linkProgramManagement,
  /** "Tambah" link that opens the Create Program form */
  linkTambahProgram:     page.getByRole('link', { name: 'Tambah' }),
});

// ── Tab: Program (main data form) ─────────────────────────────────────────────

export const tabProgramElements = (page: Page) => ({
  // ── Text inputs (stable server-rendered `name` attributes) ───────────────
  inputNama:               page.locator('input[name="NAMA"]'),
  inputKode:               page.locator('input[name="KODE"]'),
  inputThresholdExpired:   page.locator('input[name="THRESHOLD_EXPIRED_PROGRAM"]'),
  textareaInfo:            page.locator('textarea[name="INFO"]'),
  textareaKvWording:       page.locator('textarea[name="KV_WORDING"]'),
  inputRedirectLink:       page.locator('input[name="redirect_link"]'),
  inputMaxPoin:            page.locator('input[name="MAKSIMUM_JUMLAH_POIN"]'),
  inputBudget:             page.locator('input[name="BUDGET_PER_PROGRAM"]'),
  inputThresholdBudget:    page.locator('input[name="THRESHOLD_BUDGET_PROGRAM"]'),
  textareaNotifSms:        page.locator('textarea[name="NOTIFICATION_SMS"]'),

  // ── Spinbuttons (date-range / numeric pickers) ────────────────────────────
  spinbuttonTanggalMulai:  page.getByRole('spinbutton').first(),
  spinbuttonBulanMulai:    page.getByRole('spinbutton').nth(1),
  spinbuttonTanggalAkhir:  page.getByRole('spinbutton').nth(2),
  spinbuttonBulanAkhir:    page.getByRole('spinbutton').nth(3),

  // ── React-Select dropdowns ────────────────────────────────────────────────
  // ⚠️ CSS class names are auto-generated by the library.
  // Tag for replacement once `data-testid` attrs are added to the component.
  dropdownKategori:     page.locator('.css-19bb58m').first(),
  dropdownSubKategori:  page.locator('.css-hlgwow > .css-19bb58m').first(),
  dropdownProduk:       page.locator(
    '.mb-3 > .css-b62m3t-container > .css-13cymwt-control > .css-hlgwow > .css-19bb58m'
  ),
  dropdownChannel:      page.locator(
    'div:nth-child(7) > div > .css-b62m3t-container > .css-13cymwt-control > .css-hlgwow > .css-19bb58m'
  ),

  // ── Dropdown option items ─────────────────────────────────────────────────
  optionKvKategoriProgram: page.getByRole('option', { name: 'KV Kategori Program' }),
  optionKhususKv:          page.getByRole('option', { name: 'Khusus KV' }),
  optionKvProduk:          page.getByRole('option', { name: 'KV Produk' }),
  optionHaloUnlimited:     page.getByRole('option', { name: 'Halo Unlimited 80K 80rb' }),
  optionKvChannel:         page.getByRole('option', { name: 'KV Channel' }),

  // ── File upload ───────────────────────────────────────────────────────────
  uploadProgramImage: page.getByLabel('Program', { exact: true }).locator('input[type="file"]'),

  // ── Checkboxes ────────────────────────────────────────────────────────────
  checkboxTelkomsel:    page.getByRole('checkbox', { name: 'Telkomsel',     exact: true }),
  checkboxNonTelkomsel: page.getByRole('checkbox', { name: 'Non-Telkomsel'               }),

  // ── Action button ─────────────────────────────────────────────────────────
  btnSimpan: page.getByRole('button', { name: 'Simpan' }),
});

// ── Tab: Foto ─────────────────────────────────────────────────────────────────

export const tabFotoElements = (page: Page) => ({
  tabFoto:            page.getByRole('tab',     { name: 'Foto' }),
  uploadFoto:         page.getByRole('tabpanel', { name: 'Foto' }).locator('input[type="file"]'),
  inputFotoJudul:     page.locator('input[name="FOTO_JUDUL"]'),
  textareaFotoDeskripsi: page.locator('textarea[name="FOTO_DESKRIPSI"]'),
  inputWording:       page.getByRole('textbox', { name: 'Nikmati Promo {Produk} Segera' }),
  btnTambahWording:   page.getByRole('button',  { name: 'Tambah Wording' }),
});

// ── Tab: Payment Limitation ───────────────────────────────────────────────────

export const tabPaymentLimitationElements = (page: Page) => ({
  tabPaymentLimitation: page.getByRole('tab',    { name: 'Payment Limitation' }),
  btnTambah:            page.getByRole('button', { name: 'Tambah' }),
  /** Native <select> combobox for payment method selection */
  comboboxPayment:      page.getByRole('combobox'),
  /** Confirm button that saves the newly added payment row (index 1) */
  btnKonfirmasiRow:     page.getByRole('button').nth(1),
  inputTermAndCondition: page.locator('#TERM_AND_CONDITION_1'),
  btnSimpan:            page.getByRole('button', { name: 'Simpan' }),
});

// ── Tab: Sales Fee ────────────────────────────────────────────────────────────

export const tabSalesFeeElements = (page: Page) => ({
  tabSalesFee:           page.getByRole('tab',     { name: 'Sales Fee' }),
  comboboxPeriod:        page.getByRole('combobox'),
  inputAgentUpline:      page.locator('input[name="SALES_FEE.AGENT_UPLINE"]'),
  inputAgentDownline1:   page.locator('input[name="SALES_FEE.AGENT_DOWNLINE_1"]'),
  btnSimpan:             page.getByRole('button', { name: 'Simpan' }),
});

// ══════════════════════════════════════════════════════════════════════════════
// SECTION 2 – HIGH-LEVEL ACTION HELPERS
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Navigate from the dashboard to the Create Program form.
 */
export async function navigateToCreateProgram(page: Page): Promise<void> {
  const nav = programMgmtNavElements(page);
  await nav.btnManageProgram.click();
  await nav.linkProgramManagement.click();
  await nav.linkTambahProgram.click();
}

/**
 * Fill the main "Program" tab and save it.
 * @param imagePath Absolute path to the KV image file.
 */
export async function fillTabProgram(page: Page, imagePath: string): Promise<void> {
  const el = tabProgramElements(page);

  await el.inputNama.fill(form_daftar_program.name);
  await el.inputKode.fill(form_daftar_program.code);
  await el.inputThresholdExpired.fill(form_daftar_program.thresholdExpired);
  await el.textareaInfo.fill(form_daftar_program.name);

  // React-Select dropdowns
  // ⚠️ These rely on brittle CSS selectors — tag for data-testid once available.
  await el.dropdownKategori.click();
  await el.optionKvKategoriProgram.click();
  await el.dropdownSubKategori.click();
  await el.optionKhususKv.click();
  await el.dropdownSubKategori.click();
  await el.optionKvProduk.click();
  await el.dropdownProduk.click();
  await el.optionHaloUnlimited.click();

  // Date-range spinbuttons
  await el.spinbuttonTanggalMulai.fill('2');
  await el.spinbuttonBulanMulai.fill('2');
  await el.spinbuttonTanggalAkhir.fill('1');
  await el.spinbuttonBulanAkhir.fill('5');

  await el.btnSimpan.click();

  await el.textareaKvWording.fill(form_daftar_program.name);
  await el.uploadProgramImage.setInputFiles(imagePath);
  await el.inputRedirectLink.fill(form_daftar_program.redirectLink);
  await el.inputMaxPoin.fill(form_daftar_program.maxPoin);
  await el.inputBudget.fill(form_daftar_program.budget);
  await el.inputThresholdBudget.fill(form_daftar_program.thresholdBudget);

  await el.dropdownChannel.click();
  await el.optionKvChannel.click();

  await el.textareaNotifSms.fill(form_daftar_program.name);
  await el.checkboxTelkomsel.check();
  await el.checkboxNonTelkomsel.check();
}

/**
 * Switch to the Foto tab and upload a photo with its title and description.
 * @param imagePath Absolute path to the image file.
 */
export async function fillTabFoto(page: Page, imagePath: string): Promise<void> {
  const el = tabFotoElements(page);

  await el.tabFoto.click();
  await el.uploadFoto.setInputFiles(imagePath);
  await el.inputFotoJudul.fill(form_daftar_program.name);
  await el.textareaFotoDeskripsi.fill(form_daftar_program.name);
  await el.inputWording.fill(form_daftar_program.wording);
  await el.btnTambahWording.click();
}

/**
 * Switch to the Payment Limitation tab and add one payment method row.
 */
export async function fillTabPaymentLimitation(page: Page): Promise<void> {
  const el = tabPaymentLimitationElements(page);

  await el.tabPaymentLimitation.click();
  await el.btnTambah.click();
  await el.comboboxPayment.selectOption('53');
  await el.btnKonfirmasiRow.click();
  await el.inputTermAndCondition.fill(' Test Automation');
  await el.btnSimpan.click();
}

/**
 * Switch to the Sales Fee tab, set a period, fill agent fees, and save.
 */
export async function fillTabSalesFee(page: Page): Promise<void> {
  const el = tabSalesFeeElements(page);

  await el.tabSalesFee.click();
  await el.comboboxPeriod.selectOption('1');
  await el.inputAgentUpline.fill(form_daftar_program.agentUpline);
  await el.inputAgentDownline1.fill(form_daftar_program.agentDownline1);
  await el.btnSimpan.click();
}
