/**
 * helpers/elements/program-mgmt.helper.ts
 * ──────────────────────────────────────────────────────────────────────────────
 * Locators AND high-level action helpers for the Program Management feature.
 *
 * Structure:
 *   1. Element factories  – return raw Locator objects, NO side-effects.
 *   2. Action helpers     – `async` functions that accept `page` (and optionally
 *      data) and perform a meaningful business step (e.g. fillTabProgram).
 *
 * Rules (see agents.md):
 *   ✅ Element factories MUST NOT contain `await` or interaction calls.
 *   ✅ Action helpers import element factories and orchestrate clicks/fills.
 *   ✅ All names are camelCase, prefixed by their role:
 *       btn*, input*, dropdown*, checkbox*, tab*, textarea*, upload*
 * ──────────────────────────────────────────────────────────────────────────────
 */

import { Page } from '@playwright/test';
import { sidebarElements } from './global.elements';
import { TEST_DATA } from '../data.helper';

// ══════════════════════════════════════════════════════════════════════════════
// SECTION 1 – ELEMENT FACTORIES
// ══════════════════════════════════════════════════════════════════════════════

// ── Sidebar Navigation to Program Management ──────────────────────────────────

export const programMgmtNavElements = (page: Page) => ({
  btnManageProgram:      sidebarElements(page).btnManageProgram,
  linkProgramManagement: sidebarElements(page).linkProgramManagement,
  /** "Tambah" link that opens the Create Program form */
  linkTambahProgram:     page.getByRole('link', { name: 'Tambah' }),
});

// ── Tab: Program (main data form) ─────────────────────────────────────────────

export const tabProgramElements = (page: Page) => ({
  // ── Text inputs (stable server-rendered `name` attributes) ───────────────
  inputNama:               page.locator('input[name="NAMA"]'),
  inputKode:               page.locator('input[name="KODE"]'),
  inputThresholdExpired:   page.locator('input[name="THRESHOLD_EXPIRED_PROGRAM"]'),
  textareaInfo:            page.locator('textarea[name="INFO"]'),
  textareaKvWording:       page.locator('textarea[name="KV_WORDING"]'),
  inputRedirectLink:       page.locator('input[name="REDIRECT_LINK"]'),
  inputMaxPoin:            page.locator('input[name="MAKSIMUM_JUMLAH_POIN"]'),
  inputBudget:             page.locator('input[name="BUDGET_PER_PROGRAM"]'),
  inputThresholdBudget:    page.locator('input[name="THRESHOLD_BUDGET_PROGRAM"]'),
  textareaNotifSms:        page.locator('textarea[name="NOTIFICATION_SMS"]'),
  inputPromoId:            page.locator('input[name="PROMO_ID"]'),
  
  // ── Earning Poin fields (multiple inputs for different earning types) ────
  inputEarningPoin:        page.locator('input[name*="EARNING_POIN"]'),

  // ── Spinbuttons (date-range / numeric pickers) ────────────────────────────
  spinbuttonTanggalMulai:  page.getByRole('spinbutton').first(),
  spinbuttonBulanMulai:    page.getByRole('spinbutton').nth(1),
  spinbuttonTanggalAkhir:  page.getByRole('spinbutton').nth(2),
  spinbuttonBulanAkhir:    page.getByRole('spinbutton').nth(3),

  // ── React-Select dropdowns ────────────────────────────────────────────────
  // ⚠️ CSS class names are auto-generated by the library.
  // Tag for replacement once `data-testid` attrs are added to the component.
  dropdownKategori:     page.locator('.css-19bb58m').first(),
  dropdownSubKategori:  page.locator('.css-hlgwow > .css-19bb58m').first(),
  dropdownProduk:       page.locator(
    '.mb-3 > .css-b62m3t-container > .css-13cymwt-control > .css-hlgwow > .css-19bb58m'
  ),
  // ⚠️ Product dropdown in EDIT mode (different position)
  dropdownProdukEdit:   page.locator(
    'div:nth-child(10) > div > .css-b62m3t-container > .css-13cymwt-control > .css-hlgwow > .css-19bb58m'
  ),
  dropdownChannel:      page.locator(
    'div:nth-child(7) > div > .css-b62m3t-container > .css-13cymwt-control > .css-hlgwow > .css-19bb58m'
  ),
  // ⚠️ Customer Bonus dropdown - CSS class auto-generated
  dropdownCustomerBonus: page.locator('.css-b62m3t-container').filter({ hasText: 'Customer Bonus' }).locator('.css-19bb58m'),

  // ── Dropdown option items ─────────────────────────────────────────────────
  optionKvKategoriProgram: page.getByRole('option', { name: 'KV Kategori Program' }),
  optionKhususKv:          page.getByRole('option', { name: 'Khusus KV' }),
  optionKvProduk:          page.getByRole('option', { name: 'KV Produk' }),
  optionHaloUnlimited:     page.getByRole('option', { name: 'Halo Unlimited 80K 80rb' }),
  optionKvChannel:         page.getByRole('option', { name: 'KV Channel' }),

  // ── File upload ───────────────────────────────────────────────────────────
  uploadProgramImage: page.getByLabel('Program', { exact: true }).locator('input[type="file"]'),

  // ── Checkboxes ────────────────────────────────────────────────────────────
  checkboxTelkomsel:    page.getByRole('checkbox', { name: 'Telkomsel',     exact: true }),
  checkboxNonTelkomsel: page.getByRole('checkbox', { name: 'Non-Telkomsel'               }),

  // ── Action button ─────────────────────────────────────────────────────────
  btnSimpan: page.getByRole('button', { name: 'Simpan' }),
});

// ── Tab: Foto ─────────────────────────────────────────────────────────────────

export const tabFotoElements = (page: Page) => ({
  tabFoto:            page.getByRole('tab',     { name: 'Foto' }),
  uploadFoto:         page.getByRole('tabpanel', { name: 'Foto' }).locator('input[type="file"]'),
  inputFotoJudul:     page.locator('input[name="FOTO_JUDUL"]'),
  textareaFotoDeskripsi: page.locator('textarea[name="FOTO_DESKRIPSI"]'),
  inputWording:       page.getByRole('textbox', { name: 'Nikmati Promo {Produk} Segera' }),
  btnTambahWording:   page.getByRole('button',  { name: 'Tambah Wording' }),
});

// ── Tab: Payment Limitation ───────────────────────────────────────────────────

export const tabPaymentLimitationElements = (page: Page) => ({
  tabPaymentLimitation: page.getByRole('tab',    { name: 'Payment Limitation' }),
  btnTambah:            page.getByRole('button', { name: 'Tambah' }),
  /** Native <select> combobox for payment method selection */
  comboboxPayment:      page.getByRole('combobox'),
  /** Confirm button that saves the newly added payment row (index 1) */
  btnKonfirmasiRow:     page.getByRole('button').nth(1),
  inputTermAndCondition: page.locator('#TERM_AND_CONDITION_1'),
  btnSimpan:            page.getByRole('button', { name: 'Simpan' }),
});

// ── Tab: Sales Fee ────────────────────────────────────────────────────────────

export const tabSalesFeeElements = (page: Page) => ({
  tabSalesFee:           page.getByRole('tab',     { name: 'Sales Fee' }),
  comboboxPeriod:        page.getByRole('combobox'),
  inputAgentUpline:      page.locator('input[name="SALES_FEE.AGENT_UPLINE"]'),
  inputAgentDownline1:   page.locator('input[name="SALES_FEE.AGENT_DOWNLINE_1"]'),
  btnSimpan:             page.getByRole('button', { name: 'Simpan' }),
});

// ══════════════════════════════════════════════════════════════════════════════
// SECTION 2 – HIGH-LEVEL ACTION HELPERS
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Navigate from the dashboard to the Create Program form.
 */
export async function navigateToCreateProgram(page: Page): Promise<void> {
  const nav = programMgmtNavElements(page);
  await nav.btnManageProgram.click();
  // Wait for the submenu to expand before clicking the link
  await nav.linkProgramManagement.waitFor({ state: 'visible', timeout: 10_000 });
  await nav.linkProgramManagement.click();
  await nav.linkTambahProgram.click();
}

/**
 * Fill the main "Program" tab and save it.
 * @param imagePath Absolute path to the KV image file.
 */
export async function fillTabProgram(page: Page, imagePath: string): Promise<void> {
  const el = tabProgramElements(page);

  await el.inputNama.fill(TEST_DATA.program.name);
  await el.inputKode.fill(TEST_DATA.program.code);
  await el.inputThresholdExpired.fill(TEST_DATA.program.thresholdExpired);
  await el.textareaInfo.fill(TEST_DATA.program.name);
  await el.inputPromoId.fill(TEST_DATA.program.benefit);

  // React-Select dropdowns
  // ⚠️ These rely on brittle CSS selectors — tag for data-testid once available.
  await el.dropdownKategori.click();
  await el.optionKvKategoriProgram.click();
  await el.dropdownSubKategori.click();
  await el.optionKhususKv.click();
  await el.dropdownSubKategori.click();
  await el.optionKvProduk.click();
  await el.dropdownProduk.click();
  await el.optionHaloUnlimited.click();

  // Date-range spinbuttons
  await el.spinbuttonTanggalMulai.fill('2');
  await el.spinbuttonBulanMulai.fill('2');
  await el.spinbuttonTanggalAkhir.fill('1');
  await el.spinbuttonBulanAkhir.fill('5');

  await el.btnSimpan.click();

  await el.textareaKvWording.fill(TEST_DATA.program.name);
  await el.uploadProgramImage.setInputFiles(imagePath);
  await el.inputRedirectLink.fill(TEST_DATA.program.redirectLink);
  await el.inputMaxPoin.fill(TEST_DATA.program.maxPoin);
  await el.inputBudget.fill(TEST_DATA.program.budget);
  await el.inputThresholdBudget.fill(TEST_DATA.program.thresholdBudget);

  await el.dropdownChannel.click();
  await el.optionKvChannel.click();

  await el.textareaNotifSms.fill(TEST_DATA.program.name);
  await el.checkboxTelkomsel.check();
  await el.checkboxNonTelkomsel.check();
}

/**
 * Switch to the Foto tab and upload a photo with its title and description.
 * @param imagePath Absolute path to the image file.
 */
export async function fillTabFoto(page: Page, imagePath: string): Promise<void> {
  const el = tabFotoElements(page);

  await el.tabFoto.click();
  await el.uploadFoto.setInputFiles(imagePath);
  await el.inputFotoJudul.fill(TEST_DATA.program.name);
  await el.textareaFotoDeskripsi.fill(TEST_DATA.program.name);
  await el.inputWording.fill(TEST_DATA.program.wording);
  await el.btnTambahWording.click();
}

/**
 * Switch to the Payment Limitation tab and add one payment method row.
 */
export async function fillTabPaymentLimitation(page: Page): Promise<void> {
  const el = tabPaymentLimitationElements(page);

  await el.tabPaymentLimitation.click();
  await el.btnTambah.click();
  await el.comboboxPayment.selectOption('53');
  await el.btnKonfirmasiRow.click();
  await el.inputTermAndCondition.fill(' Test Automation');
  await el.btnSimpan.click();
}

/**
 * Switch to the Sales Fee tab, set a period, fill agent fees, and save.
 */
export async function fillTabSalesFee(page: Page): Promise<void> {
  const el = tabSalesFeeElements(page);

  await el.tabSalesFee.click();
  await el.comboboxPeriod.selectOption('1');
  await el.inputAgentUpline.fill(TEST_DATA.program.agentUpline);
  await el.inputAgentDownline1.fill(TEST_DATA.program.agentDownline1);
  await el.btnSimpan.click();
}

// ── Program List (for deletion and editing) ───────────────────────────────────

export const programListElements = (page: Page) => ({
  /**
   * Search input field for filtering programs by name.
   * Updated to use getByRole('textbox') with name 'Search' instead of placeholder
   */
  inputSearch: page.getByRole('textbox', { name: 'Search' }),

  /**
   * Returns the full <tr> row that contains the given program name text.
   * Scope all subsequent locators to this row to avoid acting on the wrong row.
   */
  rowByProgramName: (name: string) =>
    page.getByRole('row').filter({ hasText: name }),

  /**
   * The 🗑 delete/trash icon button inside a specific row (third button).
   * Intended usage: programListElements(page).btnDeleteInRow(row)
   */
  btnDeleteInRow: (row: ReturnType<Page['getByRole']>) =>
    row.getByRole('button').nth(2),

  /**
   * The ✏️ edit/pencil icon button inside a specific row (second button).
   * Intended usage: programListElements(page).btnEditInRow(row)
   */
  btnEditInRow: (row: ReturnType<Page['getByRole']>) =>
    row.getByRole('button').nth(1),
});

// ── Delete Confirmation Modal ─────────────────────────────────────────────────

export const deleteConfirmationElements = (page: Page) => ({
  /**
   * Confirmation button in the delete modal.
   * Usually labeled "Ya" or "Hapus" depending on the UI.
   */
  btnConfirmDelete: page.getByRole('button', { name: 'Ya' }),
});

/**
 * Navigate from the dashboard to the Program Management list page.
 */
export async function navigateToProgramManagement(page: Page): Promise<void> {
  const nav = programMgmtNavElements(page);
  await nav.btnManageProgram.click();
  // Wait for the submenu to expand before clicking the link
  await nav.linkProgramManagement.waitFor({ state: 'visible', timeout: 10_000 });
  await nav.linkProgramManagement.click();
}

/**
 * Click the 🗑 delete icon for the row matching `programName`.
 * This opens the delete confirmation modal.
 */
export async function clickDeleteIcon(page: Page, programName: string): Promise<void> {
  const list = programListElements(page);
  const row = list.rowByProgramName(programName);
  await list.btnDeleteInRow(row).click();
}

/**
 * Confirm the deletion by clicking the "Ya" button in the modal.
 */
export async function confirmDeletion(page: Page): Promise<void> {
  const modal = deleteConfirmationElements(page);
  await modal.btnConfirmDelete.click();
}

/**
 * Search for a program by name in the Program Management list.
 * @param programName The name of the program to search for.
 */
export async function searchProgram(page: Page, programName: string): Promise<void> {
  const list = programListElements(page);
  await list.inputSearch.fill(programName);
  // Wait for search results to update
  await page.waitForTimeout(1000);
}

/**
 * Click the ✏️ edit icon for the row matching `programName`.
 * This opens the edit program form.
 */
export async function clickEditIcon(page: Page, programName: string): Promise<void> {
  const list = programListElements(page);
  const row = list.rowByProgramName(programName);
  await list.btnEditInRow(row).click();
}

/**
 * Update the program name field in the edit form.
 * @param newName The new name for the program.
 */
export async function updateProgramName(page: Page, newName: string): Promise<void> {
  const el = tabProgramElements(page);
  await el.inputNama.clear();
  await el.inputNama.fill(newName);
}

/**
 * Update the program info/description field in the edit form.
 * @param newInfo The new info/description for the program.
 */
export async function updateProgramInfo(page: Page, newInfo: string): Promise<void> {
  const el = tabProgramElements(page);
  await el.textareaInfo.clear();
  await el.textareaInfo.fill(newInfo);
}

/**
 * Add a new product to the program by selecting from the product dropdown.
 * This function works for EDIT mode where the dropdown is in a different position.
 * @param productName The name of the product to add (e.g., 'Halo Unlimited 80K 80rb').
 */
export async function addProductToProgram(page: Page, productName: string): Promise<void> {
  const el = tabProgramElements(page);
  // Use the edit mode dropdown locator
  await el.dropdownProdukEdit.click();
  // Wait for dropdown options to appear
  await page.waitForTimeout(500);
  await page.getByRole('option', { name: productName }).click();
}

/**
 * Select a Customer Bonus option from the dropdown and fill Earning Poin fields in the modal.
 * This opens a modal dialog where we need to fill the Earning Poin fields.
 * @param bonusName The name of the bonus option to select.
 * @param earningPoinValue The value to fill in all 4 Earning Poin fields (e.g., '1').
 */
export async function selectCustomerBonusAndFillEarningPoin(
  page: Page,
  bonusName: string,
  earningPoinValue: string
): Promise<void> {
  // Use the exact locator from temp_codegen.txt
  await page.locator('.mb-3 > .css-b62m3t-container > .css-13cymwt-control > .css-hlgwow > .css-19bb58m').click();
  // Wait for dropdown options to appear
  await page.waitForTimeout(500);
  await page.getByRole('option', { name: bonusName }).click();
  
  // Wait for the modal dialog to appear
  const modal = page.getByRole('dialog', { name: 'Produk' });
  await modal.waitFor({ state: 'visible', timeout: 5000 });
  
  // Fill all 4 Earning Poin fields in the modal
  // The spinbuttons appear in order within the modal: Earning Poin 1, 2, 3, 4
  // We scope to the modal and get spinbuttons by index
  const spinbuttons = modal.getByRole('spinbutton');
  
  // Fill each field (indices 0-3 for Earning Poin 1-4)
  await spinbuttons.nth(0).fill(earningPoinValue); // Earning Poin 1
  await spinbuttons.nth(1).fill(earningPoinValue); // Earning Poin 2
  await spinbuttons.nth(2).fill(earningPoinValue); // Earning Poin 3
  await spinbuttons.nth(3).fill(earningPoinValue); // Earning Poin 4
  
  // Click the Simpan button in the modal to save
  await modal.getByRole('button', { name: 'Simpan' }).click();
  
  // Wait for modal to close
  await modal.waitFor({ state: 'hidden', timeout: 5000 });
}

/**
 * Change the program end date to extend the program duration.
 * This function updates the end date spinbuttons to make the program last longer.
 * @param newEndDay The new end day (e.g., '15' for day 15)
 * @param newEndMonth The new end month (e.g., '12' for December)
 */
export async function extendProgramEndDate(page: Page, newEndDay: string, newEndMonth: string): Promise<void> {
  // Use more specific locators for date fields by their name attributes
  const inputTanggalAkhir = page.locator('input[name="TANGGAL_AKHIR"]');
  const inputBulanAkhir = page.locator('input[name="BULAN_AKHIR"]');
  
  // Clear and fill the end date fields
  await inputTanggalAkhir.clear();
  await inputTanggalAkhir.fill(newEndDay);
  await inputBulanAkhir.clear();
  await inputBulanAkhir.fill(newEndMonth);
}

/**
 * Update program date range using the date picker component.
 * Follows temp_codegen.txt logic:
 * - First date: day before current day (e.g., if today is May 20th, choose May 19th)
 * - Last date: first date + 12 days (e.g., if first date is May 19th, choose May 31st)
 */
export async function updateProgramDateRange(page: Page): Promise<void> {
  // Calculate dates based on current date
  const today = new Date();
  const startDate = new Date(today);
  startDate.setDate(today.getDate() - 1); // Day before current day
  
  const endDate = new Date(startDate);
  endDate.setDate(startDate.getDate() + 12); // First date + 12 days
  
  // Format dates for the date picker
  const startDay = startDate.getDate();
  const startMonth = startDate.toLocaleString('en-US', { month: 'long' });
  const startYear = startDate.getFullYear();
  
  const endDay = endDate.getDate();
  const endMonth = endDate.toLocaleString('en-US', { month: 'long' });
  const endYear = endDate.getFullYear();
  
  // Format day with ordinal suffix (e.g., "19th", "1st", "22nd")
  const getOrdinalSuffix = (day: number): string => {
    if (day > 3 && day < 21) return 'th';
    switch (day % 10) {
      case 1: return 'st';
      case 2: return 'nd';
      case 3: return 'rd';
      default: return 'th';
    }
  };
  
  const startDayWithSuffix = `${startDay}${getOrdinalSuffix(startDay)}`;
  const endDayWithSuffix = `${endDay}${getOrdinalSuffix(endDay)}`;
  
  // Get day of week names
  const startDayOfWeek = startDate.toLocaleString('en-US', { weekday: 'long' });
  const endDayOfWeek = endDate.toLocaleString('en-US', { weekday: 'long' });
  
  // Click the date range picker to open it
  await page.getByRole('textbox', { name: 'Select date range' }).click();
  
  // Wait for calendar to appear
  await page.waitForTimeout(500);
  
  // Click the start date
  // Format: "Choose Tuesday, May 19th, 2026"
  const startDateLabel = `Choose ${startDayOfWeek}, ${startMonth} ${startDayWithSuffix}, ${startYear}`;
  await page.getByRole('gridcell', { name: startDateLabel }).click();
  
  // Click the end date
  // Format: "Choose Sunday, May 31st, 2026"
  const endDateLabel = `Choose ${endDayOfWeek}, ${endMonth} ${endDayWithSuffix}, ${endYear}`;
  await page.getByRole('gridcell', { name: endDateLabel }).click();
  
  // Wait for date picker to close
  await page.waitForTimeout(500);
}

/**
 * Save the edited program by clicking the Simpan button.
 */
export async function saveEditedProgram(page: Page): Promise<void> {
  const el = tabProgramElements(page);
  await el.btnSimpan.click();
}
